/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dnn.moduloayudanominae.main;

/**
 *
 * @author danie
 */
public class VAyuda extends javax.swing.JInternalFrame {

    /**
     * Creates new form VAyuda
     * @param titulo
     * @param descripcion
     * @param version
     * @param desarrollador
     * @param lugar
     */
    public VAyuda(String titulo, String descripcion, String version, String desarrollador, String lugar) {
        initComponents();
        this.lblTitulo.setText(titulo);
        this.lblDescripcion1.setText(descripcion);
        this.lblDesarrollador.setText(desarrollador);
        this.lblVersion.setText(version);
        this.lblLugar.setText(lugar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane1 = new javax.swing.JTabbedPane();
        InfoTab = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDesarrollador = new javax.swing.JLabel();
        lblLugar = new javax.swing.JLabel();

        setClosable(true);
        setTitle("NominaE - Ayuda");
        setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        tabPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 40)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo");

        lblVersion.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("Version");

        lblDescripcion1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lblDescripcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcion1.setText("Descripcion");

        lblDesarrollador.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lblDesarrollador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesarrollador.setText("Desarrollador");

        lblLugar.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lblLugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLugar.setText("Lugar y Fecha");

        javax.swing.GroupLayout InfoTabLayout = new javax.swing.GroupLayout(InfoTab);
        InfoTab.setLayout(InfoTabLayout);
        InfoTabLayout.setHorizontalGroup(
            InfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addComponent(lblDescripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDesarrollador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        InfoTabLayout.setVerticalGroup(
            InfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoTabLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(45, 45, 45)
                .addComponent(lblDescripcion1)
                .addGap(40, 40, 40)
                .addComponent(lblVersion)
                .addGap(33, 33, 33)
                .addComponent(lblDesarrollador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblLugar)
                .addContainerGap())
        );

        tabPane1.addTab("Aplicacion", InfoTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoTab;
    private javax.swing.JLabel lblDesarrollador;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JTabbedPane tabPane1;
    // End of variables declaration//GEN-END:variables
}
